export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DEPOSIT_AMOUNT = 'DEPOSIT_AMOUNT';
export const WITHDRAW_AMOUNT = 'WITHDRAW_AMOUNT';

// Transactions
export const SAVE_TRANSACTION = 'SAVE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

